Repository Hritvik-Mohan/Auction-Project, pull requests merged in 2022-06, with the labels that each got.

#65 Timer for all the products.
  public/js/product/indexPage.js
  views/products/edit.ejs
  views/products/index.ejs
Labels: enhancement, important

#67 Fixed Products Page UI
  public/css/styles.css
Labels: enhancement

#70 [FIX] Now the max image size that can be uploaded is 1mb
  routes/product/product.router.js
  routes/user/user.router.js
  utils/cloudinaryUpload.js
  utils/multer.js
Labels: important

#71 [FIX] Fixed the server crash after payment
  controllers/stripe-webhook/webhookEvents.js
  controllers/stripe/stripe.controller.js
  controllers/user/user.controller.js
  views/products/product.ejs
Labels: bug, important

#78 Form validation backend
  controllers/product/product.controller.js
  controllers/user/auth.controller.js
  package-lock.json
  utils/misc.functions.js
Labels: important

#79 [FIX] Hopefully fixed the timezone ISO
  controllers/product/product.controller.js
  models/product.model.js
  utils/convertTZ.js
Labels: bug, important

#82 [Update] home-page
  public/css/styles.css
  public/img/home_img.svg
  views/home.ejs
Labels: enhancement

#83 [UPDATE] Add the administrative perms to update users or products
  controllers/product/product.controller.js
  controllers/user/user.controller.js
  middlewares/isAuthorized.js
  models/product.model.js
  models/user.model.js
  routes/product/product.router.js
  routes/user/user.router.js
  views/layouts/boilerplate.ejs
  views/products/allListings.ejs
  views/users/allUsers.ejs
  views/users/edit.ejs
  views/users/index.ejs
  views/users/view.ejs
Labels: enhancement, important

#85 [BUG FIX] Fix the anchor tag link on /users route
  controllers/product/product.controller.js
  controllers/user/user.controller.js
  schemas/userSchema.js
  seeds/index.js
  seeds/products.js
  seeds/users.js
  utils/convertTZ.js
  utils/getCurrentUser.js
  views/products/allListings.ejs
Labels: bug

#89 Add email verification
  controllers/user/auth.controller.js
  controllers/user/user.controller.js
  middlewares/isAuthorized.js
  middlewares/isSeller.js
  middlewares/isTimeRemaining.js
  middlewares/isVerified.js
  middlewares/isWinner.js
  middlewares/protect.js
  middlewares/role.js
  models/user.model.js
  routes/product/product.router.js
  routes/user/user.router.js
  utils/emailTemplate.js
  utils/getCurrentUser.js
  views/users/confirmEmail.ejs
  views/users/edit.ejs
  views/users/resetPassword.ejs
  views/users/verify.ejs
Labels: enhancement, important

#90 Fix jwt expire
  app.js
  controllers/user/auth.controller.js
  middlewares/protect.js
  utils/getCurrentUser.js
Labels: bug, important

#92 [FIX] Set a max limit on bid amount at a time
  controllers/user/user.controller.js
  middlewares/isBidValid.js
  middlewares/isTimeRemaining.js
  routes/user/user.router.js
Labels: update

#93 [UPDATE] Fix return to behaviour
  controllers/user/auth.controller.js
  middlewares/protect.js
  middlewares/role.js
  public/js/product/productPage.js
  routes/user/user.router.js
  views/products/product.ejs
Labels: bug, important

#95 Email notifications
  controllers/product/product.controller.js
  controllers/user/auth.controller.js
  package-lock.json
  public/js/product/productPage.js
  utils/emailTemplate.js
  utils/emailTemplates.js
  views/products/product.ejs
Labels: bug, enhancement, important

#97 Payment success email
  controllers/stripe-webhook/webhookEvents.js
  middlewares/protect.js
  models/admin.model.js
Labels: important, update

#98 [Update] Product Page UI
  public/css/home.css
  public/css/styles.css
  public/js/product/productPage.js
  views/home.ejs
  views/products/index.ejs
  views/products/new.ejs
  views/products/product.ejs
Labels: enhancement, important

#101 [ADD] product images slider.
  public/css/styles.css
  public/js/product/productPage.js
  views/layouts/boilerplate.ejs
  views/partials/navbar.ejs
  views/products/product.ejs
Labels: enhancement, important

#105 [FIX]
  routes/user/user.router.js
  views/users/confirmEmail.ejs
  views/users/verify.ejs
Labels: update
