Repository Hritvik-Mohan/Auction-Project, pull requests merged in 2022-07, with the labels that each got.

#108 [Update] Fixed the backend validation for adding new product to the d…
  controllers/product/product.controller.js
Labels: update

#109 Refactor css
  public/css/home.css
  public/css/styles.css
  public/js/chooseFile.js
  public/js/script.js
  views/home.ejs
  views/layouts/boilerplate.ejs
  views/partials/flash.ejs
  views/partials/navbar.ejs
  views/products/edit.ejs
  views/products/index.ejs
  views/products/new.ejs
  views/products/product.ejs
  views/users/addAddress.ejs
  views/users/confirmEmail.ejs
  views/users/edit.ejs
  views/users/login.ejs
  views/users/register.ejs
Labels: enhancement, important

#112 [ADD]: Dashboard
  public/css/styles.css
  public/js/dashboard/dashboard.js
  views/layouts/boilerplate.ejs
  views/partials/navbar.ejs
  views/users/dashboard.ejs
Labels: enhancement, important

#113 [FIX]: edit.ejs
  views/products/edit.ejs
  views/products/product.ejs
Labels: bug

#114 [Update] Linked dashboard to backend.
  controllers/product/product.controller.js
  middlewares/isSeller.js
  public/js/dashboard/dashboard.js
  routes/user/user.router.js
  utils/getCurrentUser.js
  utils/getUserStats.js
  views/products/product.ejs
  views/users/dashboard.ejs
  views/users/profile.ejs
  views/users/sellerProfile.ejs
  views/users/view.ejs
Labels: update

#115 [UPDATE]
  controllers/user/auth.controller.js
  controllers/user/user.controller.js
  models/bid.model.js
  models/product.model.js
  public/js/addAddress.js
  utils/getCurrentUser.js
  views/products/edit.ejs
  views/products/new.ejs
  views/products/product.ejs
  views/users/addAddress.ejs
Labels: update

#117 [ADD] Add the requested elements
  app.js
  routes/product/product.router.js
  routes/product/v2/productv2.router.js
  routes/user/user.router.js
  utils/getUserStats.js
  views/users/dashboard/dashboard.ejs
  views/users/dashboard/myAuctions.ejs
  views/users/dashboard/myBids.ejs
Labels: enhancement, important

#118 Profile page
  public/css/styles.css
  utils/getCurrentUser.js
  views/layouts/boilerplate.ejs
  views/partials/navbar.ejs
  views/users/dashboard/dashboard.ejs
  views/users/profile.ejs
Labels: enhancement, important, update

#119 [ADD]: My auctions, my bids, & checkout page
  public/css/styles.css
  public/js/dashboard/myAuctions.js
  public/js/product/indexPage.js
  public/js/product/productPage.js
  public/js/script.js
  views/layouts/boilerplate.ejs
  views/products/checkout.ejs
  views/products/product.ejs
  views/users/dashboard/dashboard.ejs
  views/users/dashboard/myAuctions.ejs
  views/users/dashboard/myBids.ejs
Labels: enhancement, important, update

#120 [ADD]: 404 error
  public/css/styles.css
  public/img/notFound.png
  views/error.ejs
Labels: enhancement
